services:
  app:
    image: bloglist-front-dev
    build:
      context: . 
      dockerfile: bloglist-frontend/dev.Dockerfile 
    volumes:
      - ./bloglist-frontend/:/usr/src/app 
    # ports:
    #   - 5173:5173
    container_name: bloglist-front-dev 
  server1:
    image: bloglist-back-dev
    build:
      context: . 
      dockerfile: bloglist-backend/dev.Dockerfile 
    volumes:
        - ./bloglist-backend/:/usr/src/app 
    # ports:
    #   - 3000:3000
    container_name: bloglist-back-dev 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 
