services:
  app:
    image: bloglist-front-prod
    build:
      context: ./bloglist-frontend/. 
      dockerfile: Dockerfile 
    container_name: bloglist-front-prod  
  server1:
    image: bloglist-back-prod
    build:
      context: ./bloglist-backend/. 
      dockerfile: Dockerfile 
    container_name: bloglist-back-prod 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 